### ISSUE TITLE
Does includeScala = false remove the scala-library dependency?

### ISSUE THREAD

**Issue by vickumar1981** [jodersky/sbt-gpg#13]
This might be more of a question than an issue,  but does adding the line:
`assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false, includeDependency = false)`  in the `build.sbt`, remove the `scala-library` as a dependency from the published jar?

My settings:
[build.sbt](https://github.com/vickumar1981/stringdistance/commit/1ac6b0e465438cac5f530135ec759f7c6fa1a5f3)

[Maven snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/vickumar1981/stringdistance_2.12/1.1.3-SNAPSHOT/stringdistance_2.12-1.1.3-SNAPSHOT.pom)

**Comment by jodersky** [comment]
This looks like a question for sbt-assembly.

It does indeed, as described in the documentation here https://github.com/sbt/sbt-assembly#excluding-scala-library-jars
